module.exports = '<div class="top">'
    + '{'
    + '"<span class="key">name</span>" : '
    + '<div id="login" class="login">'
        + '<input id="field"/>'
        + '<button id="button">set name</button>'
    + '</div>'
    + '<span id="name" class="value"></span>'
    + ', "<span class="key">color</span>" : '
    + '<div id="colors" class="color-picker value"></div>'
    + ', "<span class="key">id</span>" : '
    + '<span id="id" class="value"></span>'
    + ', "<span class="key">magic</span>" : '
    + '<span id="magic" class="value">undefined</span>'
+ ' }</div>'
